Move entity classes to EF-Independent project
mrahhal/MR.AspNet.Identity.EntityFramework6 pull request #17
Opened 2018-03-14 04:44 UTC by ckalan

I've moved the entity classes to a separate project so that people can reference them in their model or domain projects without any requirement to reference EntityFramework. This way one can use the same model in the future with EF Core.

2018-03-14 04:48 UTC, ckalan commented
@mrahhal If you are OK with the PR, could you please upload the Model nuget package so that we can reference them in our projects?

2018-03-14 05:06 UTC, mrahhal requested changes
Sounds like a good idea.

In addition to the review comments I added that require changes, could you also rename the project from "Model" to "Models"? I'd like to follow this convention. (Make sure the folder's name is renamed too).

After those changes, I'll start releasing this as a package.

2018-03-14 05:06 UTC, mrahhal commented on src/MR.AspNet.Identity.EntityFramework6.Model/MR.AspNet.Identity.EntityFramework6.Model.csproj
> +    <Version>3.0.4</Version>
There is a common.props file that I import in all csprojs that let me share lots of those values, and also reference a single version. So please check the other csprojs on how to edit this one to take advantage of common.props. You'll still need to add the `TargetFramework` element above to override that.

2018-03-14 05:06 UTC, mrahhal commented on build.cake
> +	});
Some indentation on the last 3 lines here please. And remove the line trailing line after this.

2018-03-14 05:21 UTC, ckalan commented
I've made some changes based on your requests. Could you please check?

2018-03-14 05:22 UTC, mrahhal commented on src/MR.AspNet.Identity.EntityFramework6.Model/MR.AspNet.Identity.EntityFramework6.Model.csproj
> +  <Import Project="../../build/version.props" />
"common.props" please! It includes "version.props" and adds stuff like "PackageProjectUrl" and the like.

2018-03-14 05:25 UTC, mrahhal approved these changes
Ok looks good. I can change the project's name myself as I need to do some edits in any case. I'll merge this with another branch to do my edits.

2018-03-14 06:11 UTC, merged

2018-03-14 06:30 UTC, mrahhal commented
Fixing an issue with netstandard tfm usage. Package "MR.AspNet.Identity.EntityFramework6.Models" should be ready by today.

2018-03-14 20:02 UTC, ckalan commented
I didn't have time to fix those today. I see you've already merged it. Thanks!

2018-03-15 04:51 UTC, mrahhal commented
Released as `3.0.5`, thanks a lot!